### ISSUE TITLE
error on start with yarn: -a is required

### ISSUE THREAD

**Issue by ice09** [Neufund/smart-contract-watch#59]
On macos:
Using the example command from the README:
```
yarn start -f 4240705 -a  0x2c974b2d0ba1716e644c1fc59982a89ddd2ff724 -n "http://localhost:8545" -l "info" 
```
this error is thrown:
```
-a or --address is required
Error: -a or --address is required
```

**Comment by Moejoe90** [comment]
That is an interesting problem because in my terminal this exact command works, 
Can you try 
`yarn start -f 4240705 -a "0x2c974b2d0ba1716e644c1fc59982a89ddd2ff724" -n "http://localhost:8545" -l "debug" `
Just to see what you get.

**Comment by ice09** [comment]
it's the same then. It works with `.watch.yml`.

**Comment by ice09** [comment]
Just for reference, this is the complete stacktrace:

```
-a or --address is required
Error: -a or --address is required
    at validateParamter (/Users/alex/dev/granache/smart-contract-watch/dist/command.js:72:11)
    at exports.default (/Users/alex/dev/granache/smart-contract-watch/dist/command.js:140:16)
    at /Users/alex/dev/granache/smart-contract-watch/dist/index.js:91:67
    at Generator.next (<anonymous>)
    at step (/Users/alex/dev/granache/smart-contract-watch/dist/index.js:31:191)
    at /Users/alex/dev/granache/smart-contract-watch/dist/index.js:31:437
    at Promise (<anonymous>)
    at /Users/alex/dev/granache/smart-contract-watch/dist/index.js:31:99
    at main (/Users/alex/dev/granache/smart-contract-watch/dist/index.js:118:18)
    at Object.<anonymous> (/Users/alex/dev/granache/smart-contract-watch/dist/index.js:122:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by MostafaBalata** [comment]
hey @ice09 I tested it on my mac and its working fine, are you sure that you are using the last version from master?

**Comment by ice09** [comment]
yes, last version from master. But don't mind, if the error is in my installation, since it works with the config file, I don't mind.

**Comment by Moejoe90** [comment]
I will close this issue for now until we can find a specific reason, 
So far it was tested on Mac, Linux. and things are working as they should. 
If you have similar problems please re-open
